apiVersion: apps/v1
kind: Deployment
metadata:
  name:  testcoreapp-110520
  namespace: my-app-ns1
  labels:
    app:  testcoreapp-110520
spec:
  selector:
    matchLabels:
      app: testcoreapp-110520
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  testcoreapp-110520
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  testcoreapp-110520
        image:  locker77/core-app-abirs:15
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 120
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 120
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
