apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-dotnet-core-test
  namespace: my-app-ns1
  labels:
    app:  app-dotnet-core-test
spec:
  selector:
    matchLabels:
      app: app-dotnet-core-test
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  app-dotnet-core-test
    spec:
      containers:
      - name:  app-dotnet-core-test
        image:  locker77/core-app-abirs:15
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 120
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 120
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
